Remove `setup_logger` from COMPAT_MODULES (#9668)
In commit 5a0c4585, the deprecated `log.setup_logger` method was
removed; however `COMPAT_MODULES` didn't receive the requisite update.

The issue doesn't really manifest itself in normal usage of Celery. It
was only when using `gc.get_objects()` that it triggered a `repr` in
Celery to fail.

File "/python3.12/site-packages/celery/local.py", line 121, in __repr__
obj = self._get_current_object()
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/python3.12/site-packages/celery/local.py", line 105, in _get_current_object
return loc(*self.__args, **self.__kwargs)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/python3.12/site-packages/celery/local.py", line 390, in getappattr
return current_app._rgetattr(path)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/python3.12/site-packages/celery/app/base.py", line 1245, in _rgetattr
return attrgetter(path)(self)
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logging' object has no attribute 'setup_logger'