BROKER_FAILOVER_STRATEGY missing .. setting:: ref (Issue #1620)
The release tool complained::

<pre>
    ---> pavement.verifyconfigref
    PYTHONPATH=. /Users/asksol/.virtualenvs/def/bin/python extra/release/verify_config_reference.py             docs/configuration.rst
    Error: found undocumented settings:
    * BROKER_FAILOVER_STRATEGY
</pre>