Fixed looping through tasks instead of going through the tasks's dict keys. Prevents error like: AttributeError: 'str' object has no attribute 'link_error'